Tests in Kotlin for `NonFungibleLocalId` and `BagOfBytes`
Sajjon/RadixWalletKit pull request #33
Opened 2024-02-07 16:15 UTC by micbakos-rdx

Tests added verifying the usage of:
1. `NonFungibleLocalId`
2. `BagOfBytes`

2024-02-07 17:53 UTC, Sajjon commented on profile/tests/uniffi/bindings/test_bag_of_bytes.kts
> +val acedBugOfBytes: BagOfBytes
`BugOfBytes` :D :D :D intentional? :D

2024-02-07 18:39 UTC, Sajjon requested changes
Nice! Good job! Just change `Bug` to `Bag` in all places :)

2024-02-08 08:16 UTC, micbakos-rdx commented on profile/tests/uniffi/bindings/test_bag_of_bytes.kts
> +val acedBugOfBytes: BagOfBytes
Haha no way :P will fix.

2024-02-08 09:35 UTC, Sajjon approved these changes
LGTM

2024-02-08 09:35 UTC, merged